### ISSUE TITLE
Sending files between 2 PCs

### ISSUE THREAD

**Issue by NaiCity** [tom-james-watson/dat-cp#12]
I have 2 PCS  

1. IP 10.200.50.50 - Source 
2. IP 10.200.50.50 - Destination

I want to copy files  in  /root/docs/ from PC 1  to  /home/james/docs in PC 2.

Kindly elaborate clearly on how this can be achieved.

**Comment by NaiCity** [comment]
Sorry , PC1 is 10.200.50.50 and PC2 is 10.200.50.51

**Comment by tom-james-watson** [comment]
Hello. `dcp` requires shell access to both computers. You don't necessarily need to have access yourself to both machines, but somebody does.

On Source run:

```
dcp file1 file2 file3
```

Then, copy the public key that the above command generates. It will look something like `d2fd9b05e1e9e567d6cf244d5b2022a81268a7f7e25601f6c594005c59178f01`.

Then, on Destination run:

```
dcp d2fd9b05e1e9e567d6cf244d5b2022a81268a7f7e25601f6c594005c59178f01
```

Updating `d2fd9b05e1e9e567d6cf244d5b2022a81268a7f7e25601f6c594005c59178f01` with the actual key, obviously.

**Comment by NaiCity** [comment]
Works like a charm! Thanks.

**Comment by tom-james-watson** [comment]
Great!
