### ISSUE TITLE
can we use dat-cp "over" ssh?

### ISSUE THREAD

**Issue by jprobichaud** [tom-james-watson/dat-cp#28]
From my limited experience, dat-cp works when the two machines are on the same network.  Could I use it over the internet, say, with an ssh connection?  How does the peer "discovery" operation  works?

**Comment by tom-james-watson** [comment]
Dat will work over the Internet without needing to do anything special. No
need to use ssh or anything. See
https://datprotocol.github.io/how-dat-works/#discovery for more info.
