### ISSUE TITLE
Error if there are no files to upload or any don't exist

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/dat-cp#7]
e.g. you specify dirs only but no `-r`, or have specified `-r` but dirs are empty, or if you specify a non-existing file.

May need to check files before upload

**Comment by tom-james-watson** [comment]
Closed by https://github.com/tom-james-watson/dat-cp/commit/c662defc5519080bedb862f69e80f966cfad3749

**Comment by pepa65** [comment]
Great app!! This is the one thing I would change: do `-r` by default, and get rid of the whole flag, and the error.
Who would say `dcp <directory>` and not want the directory in its whole depth to be transferred?? Then you don't need the flag, you don't need the error, and it works as intuitively would be expected. And if `<directory>` happens to be empty, you're just receiving an empty directory, no problem, and probably what was intended!

**Comment by tom-james-watson** [comment]
I think it's still possible to have no files, e.g. `dcp dir/blob-that-matches-nothing-*`, so still need that error.

I'm not totally against getting rid of `-r` and doing recursive by default. Can at least give it some thought. You should open that as an individual issue though if you'd like to see that.

**Comment by pepa65** [comment]
Well, if you implement sending text without `--text`, you would then just send "dir/blob-that-matches-nothing-*" as a text in that case. If you really want to catch `dcp ''` -- sending an empty text string? If someone would choose to give that command, they might have some purpose for it??
